xixunyun:
  username: 201914336236
  password: 336236
  #school_id  106:生机
  school: 106
  #紧急联系人姓名
  familyName: 李素贞
  #紧急联系人电话
  familyPhone: 15080830671

#pushplues:token https://pushplus.plus/
pushplus:
  token: adeef70dc0ed4dc9bfa9634c302c443f